### ISSUE TITLE
적금 해지

### ISSUE THREAD

**Issue by aacara** [yebin-choi/kb-magic-wallet#149]
### TODO

- []  적금 해지시 모임통장에 돈 환불
  - [] 만기시 이자 포함하여 모임통장에 돈 입금
  - [] 만기 전 이자 포함하지 않고 모임통장에 돈 입금
