### ISSUE TITLE
버그 픽스 - 염혜정

### ISSUE THREAD

**Issue by cyzlcyzl** [yebin-choi/kb-magic-wallet#216]
### TODO

- [x] 오프라인 환전 내역 날짜 포멧 변경 + ALert 지우기
- [x] 모임지갑 채우기 화면 + 개인지갑 내역 Insert하기(이체 출금)
- [x] 모임지갑 꺼내기 화면 + 개인지갑 내역 Insert하기(이체 입금)
