### ISSUE TITLE
Refactoring - 김진형

### ISSUE THREAD

**Issue by JinHxxxxKim** [yebin-choi/kb-magic-wallet#249]
### TODO

- [ ] 모달창 디자인 변경
- [ ] 카드 연결내역 픽토그램
- [ ] 로그인 창 모달로 변경
